on:
  schedule:
    - cron: "0 16 * * 1"
  workflow_dispatch: 
    inputs:
      make_release: 
        description: "Make release? (or just pull data and commit it)"
        type: boolean
      release_tag:
        description: "Release tag (leave blank for today's date or increment to e.g. 2026-01-01.1 for a second release of the day)"
        type: string

name: archive-data.yaml

permissions: 
  contents: write

jobs:
  archive-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Download CSVs
        run: |
          for agency in nih ahrq nsf cdc epa samhsa; do
            wget -b -a wget-log -O data/$agency.csv https://data.grant-witness.us/$agency/dl-table.csv
          done
          
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
     
      # This might not be necessary—could try leaving publication_date blank to
      # see if Zenodo sets it to the upload date
      - name: Update release date
        run: | 
          cat .zenodo.json | jq --arg DATE "$DATE" '.publication_date |= $DATE' > .zenodo.json.tmp &&
          mv .zenodo.json.tmp .zenodo.json
        env:
          DATE: ${{ steps.date.outputs.date }}
      
      - uses: actions/upload-artifact@v7
        with:
          name: wget-log
          path: wget-log
        
      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Automated data update
          file_pattern: 'data/*'
      - name: Create release
        if: ${{ (github.event_name=='workflow_dispatch' && github.event.inputs.make_release == 'true') || github.event_name=='schedule' }}
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.event.inputs.release_tag || steps.date.outputs.date }}
        