on:
  # TODO: add cron job
  workflow_dispatch: # TODO: add controls of whether to make the release or not

name: archive-data.yaml

permissions: 
  contents: write

jobs:
  archive-data:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}

      - name: Download CSVs
        run: |
          for agency in nih ahrq nsf cdc epa samhsa; do
            wget -b -a wget-log -O data/$agency.csv https://data.grant-witness.us/$agency/dl-table.csv
          done
     
      - name: Update release date
        run: | 
          sed -e "s|date-released: '[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}'|date-released: '$(date +%Y-%m-%d)'|" CITATION.cff > CITATION.cff.tmp &&
          mv CITATION.cff.tmp CITATION.cff
          
      ## Probably not necessary and involves installing R and `cffr` package. 
      # - name: Validate CITATION.cff
      #   uses: dieghernan/cff-validator@v5
      
      - uses: actions/upload-artifact@v7
        with:
          name: wget-log
          path: wget-log
        
      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Automated data update
          file_pattern: 'data/*'
      # TODO create release
        